# Generated by Django 3.1.5 on 2022-04-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('l_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('e_mail', models.CharField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
            ],
        ),
    ]
