# Generated by Django 3.1.5 on 2022-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220422_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('e_mail', models.CharField(max_length=100, verbose_name='Email')),
                ('msg', models.TextField(max_length=100, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'UserData', 'verbose_name_plural': 'UserDates'},
        ),
    ]
